version: '3'

services:
    blazegraph:
        image: blazegraph_img
        volumes:
            - ./blazegraph.jar/:/blazegraph/blazegraph.jar
            - ./../../data:/data
        ports:
            - "9999:9999"
        container_name: blazegraph
        tty: true